--
-- PostgreSQL database dump
--

\restrict eGa76RuJpZEFa8WZv6sO4R2C2Ub8vgSeWWwZSSvd4nPPithZsRaZ0E3G8Z8DGFb

-- Dumped from database version 18.4 (Ubuntu 18.4-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comments; Type: TABLE; Schema: public; Owner: rahma
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    message character varying(255),
    idea_id bigint,
    user_id bigint
);


ALTER TABLE public.comments OWNER TO rahma;

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: rahma
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedbacks; Type: TABLE; Schema: public; Owner: rahma
--

CREATE TABLE public.feedbacks (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    comment character varying(255),
    idea_id bigint,
    lecturer_id bigint
);


ALTER TABLE public.feedbacks OWNER TO rahma;

--
-- Name: feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: rahma
--

ALTER TABLE public.feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ideas; Type: TABLE; Schema: public; Owner: rahma
--

CREATE TABLE public.ideas (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    category character varying(255) NOT NULL,
    description character varying(255),
    status character varying(255) NOT NULL,
    title character varying(255),
    user_id bigint,
    CONSTRAINT ideas_category_check CHECK (((category)::text = ANY ((ARRAY['AGRICULTURE'::character varying, 'EDUCATION'::character varying, 'HEALTHCARE'::character varying, 'TECHNOLOGY'::character varying, 'ENVIRONMENT'::character varying, 'BUSINESS'::character varying, 'FINANCE'::character varying, 'SECURITY'::character varying, 'TRANSPORTATION'::character varying, 'WATER_AND_HYGIENE'::character varying, 'TOURISM'::character varying, 'BLUE_ECONOMY'::character varying, 'RENEWABLE_ENERGY'::character varying, 'FINTECH'::character varying, 'OTHERS'::character varying])::text[]))),
    CONSTRAINT ideas_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'UNDER_REVIEW'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'IMPLEMENTED'::character varying])::text[])))
);


ALTER TABLE public.ideas OWNER TO rahma;

--
-- Name: ideas_id_seq; Type: SEQUENCE; Schema: public; Owner: rahma
--

ALTER TABLE public.ideas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ideas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: rahma
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'LECTURER'::character varying, 'STUDENT'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO rahma;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: rahma
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: votes; Type: TABLE; Schema: public; Owner: rahma
--

CREATE TABLE public.votes (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp(6) without time zone,
    idea_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.votes OWNER TO rahma;

--
-- Name: votes_id_seq; Type: SEQUENCE; Schema: public; Owner: rahma
--

ALTER TABLE public.votes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: rahma
--

COPY public.comments (id, created_by, created_date, last_modified_by, last_modified_date, message, idea_id, user_id) FROM stdin;
1	\N	\N	\N	\N	This is a great idea. It can help farmers increase crop production and reduce water waste.	1	6
2	\N	\N	\N	\N	Very useful for students. It will make it easier to recover lost items on campus.	2	7
3	\N	\N	\N	\N	This system will improve access to healthcare services and reduce waiting time for students.	3	5
\.


--
-- Data for Name: feedbacks; Type: TABLE DATA; Schema: public; Owner: rahma
--

COPY public.feedbacks (id, created_by, created_date, last_modified_by, last_modified_date, comment, idea_id, lecturer_id) FROM stdin;
\.


--
-- Data for Name: ideas; Type: TABLE DATA; Schema: public; Owner: rahma
--

COPY public.ideas (id, created_by, created_date, last_modified_by, last_modified_date, category, description, status, title, user_id) FROM stdin;
1	\N	\N	\N	\N	AGRICULTURE	A system that uses sensors to monitor soil moisture,temperature, and crop conditions to help farmers improve production.	PENDING	Smart Agriculture Monitoring System	5
2	\N	\N	\N	\N	AGRICULTURE	A system that uses sensors to monitor soil moisture,temperature, and crop conditions to help farmers improve production.	PENDING	Smart Agriculture Monitoring System	5
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: rahma
--

COPY public.users (id, created_by, created_date, last_modified_by, last_modified_date, email, first_name, last_name, password, role) FROM stdin;
1	\N	\N	\N	\N	admin@uic.com	System	Admin	$2a$10$G5ubEMRKfxDIe54mhsCdQ.FMn.qpbbftNVqy4ypit8pK4rSV1YEdq	ADMIN
2	\N	\N	\N	\N	asha@suza.ac.tz	Asha	Ali	$2a$10$KZ0qrtFZ/pSdpYykbB/vpem6NvEvovaJEDAHbQL6hLeSTsLtqUEbi	LECTURER
3	\N	\N	\N	\N	hassan@suza.ac.tz	Hassan	Said	$2a$10$exr1gF/P5PgmsQ0XxT/Wx.uMvrDhHMFxccdez1oW.0.dVI7wjB3Aq	LECTURER
4	\N	\N	\N	\N	fatma@suza.ac.tz	Fatma	Salim	$2a$10$Ya6EGhMK0zPSEwDM87zRoeG62BTT40uPWsR2qYprFmdA.5MxSUf/2	LECTURER
5	\N	\N	\N	\N	rahma@stu.suza.ac.tz	Rahma	Suleiman	$2a$10$V5plsd.7SGtQuNZl2ITUreSSLy6HUC2uxtrUn0dC75rYgg1eR3zai	STUDENT
6	\N	\N	\N	\N	shuayb@stu.suza.ac.tz	Shuayb	Mohamed	$2a$10$rnc9VV79UpWavTDree7UMOAdfG/PIujQRap6JTBFtjhom64almdfW	STUDENT
7	\N	\N	\N	\N	zainab@stu.suza.ac.tz	Zainab	Hassan	$2a$10$fE9mW3SF8Jiv11pxOVof3O.hn.dlRY9IrJM7MqqM/.1hkwrDVQ1UG	STUDENT
\.


--
-- Data for Name: votes; Type: TABLE DATA; Schema: public; Owner: rahma
--

COPY public.votes (id, created_by, created_date, last_modified_by, last_modified_date, idea_id, user_id) FROM stdin;
1	\N	\N	\N	\N	1	6
2	\N	\N	\N	\N	1	7
3	\N	\N	\N	\N	2	5
4	\N	\N	\N	\N	2	7
5	\N	\N	\N	\N	3	5
6	\N	\N	\N	\N	3	6
\.


--
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rahma
--

SELECT pg_catalog.setval('public.comments_id_seq', 3, true);


--
-- Name: feedbacks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rahma
--

SELECT pg_catalog.setval('public.feedbacks_id_seq', 1, false);


--
-- Name: ideas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rahma
--

SELECT pg_catalog.setval('public.ideas_id_seq', 2, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rahma
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- Name: votes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rahma
--

SELECT pg_catalog.setval('public.votes_id_seq', 6, true);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: feedbacks feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT feedbacks_pkey PRIMARY KEY (id);


--
-- Name: ideas ideas_pkey; Type: CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.ideas
    ADD CONSTRAINT ideas_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: votes ukdqudrua44puq3rx7amqp2x9l4; Type: CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.votes
    ADD CONSTRAINT ukdqudrua44puq3rx7amqp2x9l4 UNIQUE (idea_id, user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: votes votes_pkey; Type: CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.votes
    ADD CONSTRAINT votes_pkey PRIMARY KEY (id);


--
-- Name: feedbacks fk2ndrdfe1lfq990n0px1elru5r; Type: FK CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT fk2ndrdfe1lfq990n0px1elru5r FOREIGN KEY (lecturer_id) REFERENCES public.users(id);


--
-- Name: feedbacks fk3wvenqtrefygt73t5afkj8ten; Type: FK CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT fk3wvenqtrefygt73t5afkj8ten FOREIGN KEY (idea_id) REFERENCES public.ideas(id);


--
-- Name: comments fk8omq0tc18jd43bu5tjh6jvraq; Type: FK CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: votes fkli4uj3ic2vypf5pialchj925e; Type: FK CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.votes
    ADD CONSTRAINT fkli4uj3ic2vypf5pialchj925e FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: ideas fkt4qp1368gdn4wk6ih62bj80ym; Type: FK CONSTRAINT; Schema: public; Owner: rahma
--

ALTER TABLE ONLY public.ideas
    ADD CONSTRAINT fkt4qp1368gdn4wk6ih62bj80ym FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict eGa76RuJpZEFa8WZv6sO4R2C2Ub8vgSeWWwZSSvd4nPPithZsRaZ0E3G8Z8DGFb

