spring.application.name=innovationConnect

spring.datasource.url=jdbc:postgresql://localhost:5432/uni_inno_connect
spring.datasource.username=rahma
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# EXPORT DATABASE
# pg_dump -U rahma -d uni_inno_connect > uni_inno_connect_backup.sql
# It will ask:Password:Enter:12345
# Now check: ls
# IMPORT DATABASE
# First create the database(IF U DONT HV): 
# createdb -U rahma uni_inno_connect

# Then import:
# psql -U rahma -d uni_inno_connect < uni_inno_connect_backup.sql

# Enter password: 12345